version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      # Install flit
      - pip install flit
      # Install the package with development dependencies
      - flit install --deps develop --symlink

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
