hmdb: 
  atom_type: ['C', 'O', 'N', 'H', 'P', 'S', 'F', 'Cl', 'B', 'Br', 'I']
  max_atom_num: 300
  min_atom_num: 10
  precursor_type: ['[M+H]+', '[M-H]-', '[M+H-H2O]+', '[M+Na]+', '[M+2H]2+']

# encoding ======================================================================
encoding:
  resolution: 0.2
  max_mz: 1500

  conf_type: 'origin' 
  atom_type: 
    'C': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    'H': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    'O': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    'N': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
    'F': [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
    'S': [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
    'Cl': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
    'P': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
    'B': [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
    'Br': [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
    'I': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
  max_atom_num: 300

  precursor_type:
    '[M+H]+': [1, 0, 0, 0, 0]
    '[M-H]-': [0, 1, 0, 0, 0]
    '[M+H-H2O]+': [0, 0, 1, 0, 0]
    '[M+Na]+': [0, 0, 0, 1, 0]
    '[M+2H]2+': [0, 0, 0, 0, 1]

  type2charge:
    '[M+H]+': '1'
    '[M-H]-': '1'
    '[M+H-H2O]+': '1'
    '[M+Na]+': '1'
    '[M+2H]2+': '2'
